version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg_db
    environment:
      POSTGRES_DB: MoEngage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: moengage_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/MoEngage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
      ddl-auto: update

volumes:
  pg_data:
